#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using lbcLibrary;


namespace lbcLibrary	
{	
	public partial class LbcDbContext : OpenAccessContext
	{
		private static string connectionStringName = @"lbcDbConnection";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
		
			
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("lbcDomainModel.rlinq");
	
		public LbcDbContext()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public LbcDbContext(string connection)
			:base(connection, backend, metadataSource)
		{ }
	
		public LbcDbContext(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public LbcDbContext(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public LbcDbContext(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Course> Courses 
		{
	    	get
	    	{
	        	return this.GetAll<Course>();
	    	}
		}

        public IObjectScope Scope
        {
            get
            {
                return this.GetScope();
            }
        }
		
		public IQueryable<CoursePermission> CoursePermissions 
		{
	    	get
	    	{
	        	return this.GetAll<CoursePermission>();
	    	}
		}
		
		public IQueryable<DepthOfKnowledge> DepthOfKnowledges 
		{
	    	get
	    	{
	        	return this.GetAll<DepthOfKnowledge>();
	    	}
		}
		
		public IQueryable<DistrictObjective> DistrictObjectives 
		{
	    	get
	    	{
	        	return this.GetAll<DistrictObjective>();
	    	}
		}
		
		public IQueryable<Document> Documents 
		{
	    	get
	    	{
	        	return this.GetAll<Document>();
	    	}
		}
		
		public IQueryable<EssentialSkill> EssentialSkills 
		{
	    	get
	    	{
	        	return this.GetAll<EssentialSkill>();
	    	}
		}
		
		public IQueryable<ExpectationIndex> ExpectationIndices 
		{
	    	get
	    	{
	        	return this.GetAll<ExpectationIndex>();
	    	}
		}
		
		public IQueryable<Expectation> Expectations 
		{
	    	get
	    	{
	        	return this.GetAll<Expectation>();
	    	}
		}
		
		public IQueryable<KnowledgeStandard> KnowledgeStandards 
		{
	    	get
	    	{
	        	return this.GetAll<KnowledgeStandard>();
	    	}
		}
		
		public IQueryable<LbcUser> LbcUsers 
		{
	    	get
	    	{
	        	return this.GetAll<LbcUser>();
	    	}
		}
		
		public IQueryable<Lesson> Lessons 
		{
	    	get
	    	{
	        	return this.GetAll<Lesson>();
	    	}
		}
		
		public IQueryable<LessonExpectation> LessonExpectations 
		{
	    	get
	    	{
	        	return this.GetAll<LessonExpectation>();
	    	}
		}
		
		public IQueryable<LessonObjective> LessonObjectives 
		{
	    	get
	    	{
	        	return this.GetAll<LessonObjective>();
	    	}
		}
		
		public IQueryable<MyDescription> MyDescriptions 
		{
	    	get
	    	{
	        	return this.GetAll<MyDescription>();
	    	}
		}
		
		public IQueryable<MyMaterial> MyMaterials 
		{
	    	get
	    	{
	        	return this.GetAll<MyMaterial>();
	    	}
		}
		
		public IQueryable<MyMHLE> MyMHLEs 
		{
	    	get
	    	{
	        	return this.GetAll<MyMHLE>();
	    	}
		}
		
		public IQueryable<MyModification> MyModifications 
		{
	    	get
	    	{
	        	return this.GetAll<MyModification>();
	    	}
		}
		
		public IQueryable<ProcessStandard> ProcessStandards 
		{
	    	get
	    	{
	        	return this.GetAll<ProcessStandard>();
	    	}
		}
		
		public IQueryable<Unit> Units 
		{
	    	get
	    	{
	        	return this.GetAll<Unit>();
	    	}
		}
		
		public IQueryable<LessonMyDescription> LessonMyDescriptions 
		{
	    	get
	    	{
	        	return this.GetAll<LessonMyDescription>();
	    	}
		}
		
		public IQueryable<LessonMyDocument> LessonMyDocuments 
		{
	    	get
	    	{
	        	return this.GetAll<LessonMyDocument>();
	    	}
		}
		
		public IQueryable<LessonMyMaterial> LessonMyMaterials 
		{
	    	get
	    	{
	        	return this.GetAll<LessonMyMaterial>();
	    	}
		}
		
		public IQueryable<LessonMyMHLE> LessonMyMHLEs 
		{
	    	get
	    	{
	        	return this.GetAll<LessonMyMHLE>();
	    	}
		}
		
		public IQueryable<LessonMyModification> LessonMyModifications 
		{
	    	get
	    	{
	        	return this.GetAll<LessonMyModification>();
	    	}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "mssql";
			return backend;
		}
	}
}

namespace lbcLibrary	
{
	public partial class Course
	{
		private Guid iD;
		public virtual Guid ID 
		{ 
		    get
		    {
		        return this.iD;
		    }
		    set
		    {
		        this.iD = value;
		    }
		}
		
		private string name;
		public virtual string Name 
		{ 
		    get
		    {
		        return this.name;
		    }
		    set
		    {
		        this.name = value;
		    }
		}
		
		private string grade;
		public virtual string Grade 
		{ 
		    get
		    {
		        return this.grade;
		    }
		    set
		    {
		        this.grade = value;
		    }
		}
		
		private System.Nullable<System.Guid> createdBy;
		public virtual System.Nullable<System.Guid> CreatedBy 
		{ 
		    get
		    {
		        return this.createdBy;
		    }
		    set
		    {
		        this.createdBy = value;
		    }
		}
		
		private string alignment;
		public virtual string Alignment 
		{ 
		    get
		    {
		        return this.alignment;
		    }
		    set
		    {
		        this.alignment = value;
		    }
		}
		
		private long? expectationCodeStart;
		public virtual long? ExpectationCodeStart 
		{ 
		    get
		    {
		        return this.expectationCodeStart;
		    }
		    set
		    {
		        this.expectationCodeStart = value;
		    }
		}
		
		private long? expectationCodeStop;
		public virtual long? ExpectationCodeStop 
		{ 
		    get
		    {
		        return this.expectationCodeStop;
		    }
		    set
		    {
		        this.expectationCodeStop = value;
		    }
		}
		
		private string philosophy;
		public virtual string Philosophy 
		{ 
		    get
		    {
		        return this.philosophy;
		    }
		    set
		    {
		        this.philosophy = value;
		    }
		}
		
		private string rationale;
		public virtual string Rationale 
		{ 
		    get
		    {
		        return this.rationale;
		    }
		    set
		    {
		        this.rationale = value;
		    }
		}
		
		private string description;
		public virtual string Description 
		{ 
		    get
		    {
		        return this.description;
		    }
		    set
		    {
		        this.description = value;
		    }
		}
		
		private DateTime? dateApproved;
		public virtual DateTime? DateApproved 
		{ 
		    get
		    {
		        return this.dateApproved;
		    }
		    set
		    {
		        this.dateApproved = value;
		    }
		}
		
		private System.Nullable<System.Guid> alignment1;
		public virtual System.Nullable<System.Guid> Alignment1 
		{ 
		    get
		    {
		        return this.alignment1;
		    }
		    set
		    {
		        this.alignment1 = value;
		    }
		}
		
		private System.Nullable<System.Guid> alignment2;
		public virtual System.Nullable<System.Guid> Alignment2 
		{ 
		    get
		    {
		        return this.alignment2;
		    }
		    set
		    {
		        this.alignment2 = value;
		    }
		}
		
		private IList<DistrictObjective> districtObjectives = new List<DistrictObjective>();
		public virtual IList<DistrictObjective> DistrictObjectives 
		{ 
		    get
		    {
		        return this.districtObjectives;
		    }
		}
		
		private IList<EssentialSkill> essentialSkills = new List<EssentialSkill>();
		public virtual IList<EssentialSkill> EssentialSkills 
		{ 
		    get
		    {
		        return this.essentialSkills;
		    }
		}
		
		private IList<CoursePermission> coursePermissions = new List<CoursePermission>();
		public virtual IList<CoursePermission> CoursePermissions 
		{ 
		    get
		    {
		        return this.coursePermissions;
		    }
		}
		
		private IList<Unit> units = new List<Unit>();
		public virtual IList<Unit> Units 
		{ 
		    get
		    {
		        return this.units;
		    }
		}
		
	}
}

namespace lbcLibrary	
{
	public partial class CoursePermission
	{
		private Guid courseID;
		public virtual Guid CourseID 
		{ 
		    get
		    {
		        return this.courseID;
		    }
		    set
		    {
		        this.courseID = value;
		    }
		}
		
		private Guid userID;
		public virtual Guid UserID 
		{ 
		    get
		    {
		        return this.userID;
		    }
		    set
		    {
		        this.userID = value;
		    }
		}
		
		private string permission;
		public virtual string Permission 
		{ 
		    get
		    {
		        return this.permission;
		    }
		    set
		    {
		        this.permission = value;
		    }
		}
		
		private Course course;
		public virtual Course Course 
		{ 
		    get
		    {
		        return this.course;
		    }
		    set
		    {
		        this.course = value;
		    }
		}
		
		private LbcUser lbcUser;
		public virtual LbcUser LbcUser 
		{ 
		    get
		    {
		        return this.lbcUser;
		    }
		    set
		    {
		        this.lbcUser = value;
		    }
		}
		
	}
}

namespace lbcLibrary	
{
	public partial class DepthOfKnowledge
	{
		private Guid iD;
		public virtual Guid ID 
		{ 
		    get
		    {
		        return this.iD;
		    }
		    set
		    {
		        this.iD = value;
		    }
		}
		
		private short level;
		public virtual short Level 
		{ 
		    get
		    {
		        return this.level;
		    }
		    set
		    {
		        this.level = value;
		    }
		}
		
		private string link;
		public virtual string Link 
		{ 
		    get
		    {
		        return this.link;
		    }
		    set
		    {
		        this.link = value;
		    }
		}
		
	}
}

namespace lbcLibrary	
{
	public partial class DistrictObjective
	{
		private Guid iD;
		public virtual Guid ID 
		{ 
		    get
		    {
		        return this.iD;
		    }
		    set
		    {
		        this.iD = value;
		    }
		}
		
		private string number;
		public virtual string Number 
		{ 
		    get
		    {
		        return this.number;
		    }
		    set
		    {
		        this.number = value;
		    }
		}
		
		private string description;
		public virtual string Description 
		{ 
		    get
		    {
		        return this.description;
		    }
		    set
		    {
		        this.description = value;
		    }
		}
		
		private IList<Course> courses = new List<Course>();
		public virtual IList<Course> Courses 
		{ 
		    get
		    {
		        return this.courses;
		    }
		}
		
		private IList<Unit> units = new List<Unit>();
		public virtual IList<Unit> Units 
		{ 
		    get
		    {
		        return this.units;
		    }
		}
		
	}
}

namespace lbcLibrary	
{
	public partial class Document
	{
		private Guid iD;
		public virtual Guid ID 
		{ 
		    get
		    {
		        return this.iD;
		    }
		    set
		    {
		        this.iD = value;
		    }
		}
		
		private string filename;
		public virtual string Filename 
		{ 
		    get
		    {
		        return this.filename;
		    }
		    set
		    {
		        this.filename = value;
		    }
		}
		
		private string filePath;
		public virtual string FilePath 
		{ 
		    get
		    {
		        return this.filePath;
		    }
		    set
		    {
		        this.filePath = value;
		    }
		}
		
		private IList<Lesson> lessons = new List<Lesson>();
		public virtual IList<Lesson> Lessons 
		{ 
		    get
		    {
		        return this.lessons;
		    }
		}
		
		private IList<LessonMyDocument> lessonMyDocuments = new List<LessonMyDocument>();
		public virtual IList<LessonMyDocument> LessonMyDocuments 
		{ 
		    get
		    {
		        return this.lessonMyDocuments;
		    }
		}
		
	}
}

namespace lbcLibrary	
{
	public partial class EssentialSkill
	{
		private Guid iD;
		public virtual Guid ID 
		{ 
		    get
		    {
		        return this.iD;
		    }
		    set
		    {
		        this.iD = value;
		    }
		}
		
		private string number;
		public virtual string Number 
		{ 
		    get
		    {
		        return this.number;
		    }
		    set
		    {
		        this.number = value;
		    }
		}
		
		private string description;
		public virtual string Description 
		{ 
		    get
		    {
		        return this.description;
		    }
		    set
		    {
		        this.description = value;
		    }
		}
		
		private IList<Course> courses = new List<Course>();
		public virtual IList<Course> Courses 
		{ 
		    get
		    {
		        return this.courses;
		    }
		}
		
		private IList<Lesson> lessons = new List<Lesson>();
		public virtual IList<Lesson> Lessons 
		{ 
		    get
		    {
		        return this.lessons;
		    }
		}
		
	}
}

namespace lbcLibrary	
{
	public partial class ExpectationIndex
	{
		private int source;
		public virtual int Source 
		{ 
		    get
		    {
		        return this.source;
		    }
		    set
		    {
		        this.source = value;
		    }
		}
		
		private int grade;
		public virtual int Grade 
		{ 
		    get
		    {
		        return this.grade;
		    }
		    set
		    {
		        this.grade = value;
		    }
		}
		
		private int area;
		public virtual int Area 
		{ 
		    get
		    {
		        return this.area;
		    }
		    set
		    {
		        this.area = value;
		    }
		}
		
		private int course;
		public virtual int Course 
		{ 
		    get
		    {
		        return this.course;
		    }
		    set
		    {
		        this.course = value;
		    }
		}
		
		private int version;
		public virtual int Version 
		{ 
		    get
		    {
		        return this.version;
		    }
		    set
		    {
		        this.version = value;
		    }
		}
		
		private string txtsource;
		public virtual string Txtsource 
		{ 
		    get
		    {
		        return this.txtsource;
		    }
		    set
		    {
		        this.txtsource = value;
		    }
		}
		
		private string txtgrade;
		public virtual string Txtgrade 
		{ 
		    get
		    {
		        return this.txtgrade;
		    }
		    set
		    {
		        this.txtgrade = value;
		    }
		}
		
		private string txtarea;
		public virtual string Txtarea 
		{ 
		    get
		    {
		        return this.txtarea;
		    }
		    set
		    {
		        this.txtarea = value;
		    }
		}
		
		private string txtcourse;
		public virtual string Txtcourse 
		{ 
		    get
		    {
		        return this.txtcourse;
		    }
		    set
		    {
		        this.txtcourse = value;
		    }
		}
		
		private int count;
		public virtual int Count 
		{ 
		    get
		    {
		        return this.count;
		    }
		    set
		    {
		        this.count = value;
		    }
		}
		
		private string type;
		public virtual string Type 
		{ 
		    get
		    {
		        return this.type;
		    }
		    set
		    {
		        this.type = value;
		    }
		}
		
		private string revised;
		public virtual string Revised 
		{ 
		    get
		    {
		        return this.revised;
		    }
		    set
		    {
		        this.revised = value;
		    }
		}
		
		private string codeStart;
		public virtual string CodeStart 
		{ 
		    get
		    {
		        return this.codeStart;
		    }
		    set
		    {
		        this.codeStart = value;
		    }
		}
		
		private string codeEnd;
		public virtual string CodeEnd 
		{ 
		    get
		    {
		        return this.codeEnd;
		    }
		    set
		    {
		        this.codeEnd = value;
		    }
		}
		
		private string description;
		public virtual string Description 
		{ 
		    get
		    {
		        return this.description;
		    }
		    set
		    {
		        this.description = value;
		    }
		}
		
		private string dateadded;
		public virtual string Dateadded 
		{ 
		    get
		    {
		        return this.dateadded;
		    }
		    set
		    {
		        this.dateadded = value;
		    }
		}
		
		private string datemodified;
		public virtual string Datemodified 
		{ 
		    get
		    {
		        return this.datemodified;
		    }
		    set
		    {
		        this.datemodified = value;
		    }
		}
		
	}
}

namespace lbcLibrary	
{
	public partial class Expectation
	{
		private short? source;
		public virtual short? Source 
		{ 
		    get
		    {
		        return this.source;
		    }
		    set
		    {
		        this.source = value;
		    }
		}
		
		private short? gradecode;
		public virtual short? Gradecode 
		{ 
		    get
		    {
		        return this.gradecode;
		    }
		    set
		    {
		        this.gradecode = value;
		    }
		}
		
		private short? area;
		public virtual short? Area 
		{ 
		    get
		    {
		        return this.area;
		    }
		    set
		    {
		        this.area = value;
		    }
		}
		
		private short? course;
		public virtual short? Course 
		{ 
		    get
		    {
		        return this.course;
		    }
		    set
		    {
		        this.course = value;
		    }
		}
		
		private short? version;
		public virtual short? Version 
		{ 
		    get
		    {
		        return this.version;
		    }
		    set
		    {
		        this.version = value;
		    }
		}
		
		private short? reference;
		public virtual short? Reference 
		{ 
		    get
		    {
		        return this.reference;
		    }
		    set
		    {
		        this.reference = value;
		    }
		}
		
		private long senumber;
		public virtual long Senumber 
		{ 
		    get
		    {
		        return this.senumber;
		    }
		    set
		    {
		        this.senumber = value;
		    }
		}
		
		private string contentarea;
		public virtual string Contentarea 
		{ 
		    get
		    {
		        return this.contentarea;
		    }
		    set
		    {
		        this.contentarea = value;
		    }
		}
		
		private string grade;
		public virtual string Grade 
		{ 
		    get
		    {
		        return this.grade;
		    }
		    set
		    {
		        this.grade = value;
		    }
		}
		
		private string code;
		public virtual string Code 
		{ 
		    get
		    {
		        return this.code;
		    }
		    set
		    {
		        this.code = value;
		    }
		}
		
		private string contentstandard;
		public virtual string Contentstandard 
		{ 
		    get
		    {
		        return this.contentstandard;
		    }
		    set
		    {
		        this.contentstandard = value;
		    }
		}
		
		private string goals;
		public virtual string Goals 
		{ 
		    get
		    {
		        return this.goals;
		    }
		    set
		    {
		        this.goals = value;
		    }
		}
		
		private string dok;
		public virtual string Dok 
		{ 
		    get
		    {
		        return this.dok;
		    }
		    set
		    {
		        this.dok = value;
		    }
		}
		
		private string sedescription;
		public virtual string Sedescription 
		{ 
		    get
		    {
		        return this.sedescription;
		    }
		    set
		    {
		        this.sedescription = value;
		    }
		}
		
		private string datemodified;
		public virtual string Datemodified 
		{ 
		    get
		    {
		        return this.datemodified;
		    }
		    set
		    {
		        this.datemodified = value;
		    }
		}
		
		private string dateadded;
		public virtual string Dateadded 
		{ 
		    get
		    {
		        return this.dateadded;
		    }
		    set
		    {
		        this.dateadded = value;
		    }
		}
		
		private string concept;
		public virtual string Concept 
		{ 
		    get
		    {
		        return this.concept;
		    }
		    set
		    {
		        this.concept = value;
		    }
		}
		
		private string bigidea;
		public virtual string Bigidea 
		{ 
		    get
		    {
		        return this.bigidea;
		    }
		    set
		    {
		        this.bigidea = value;
		    }
		}
		
		private string coursemeta;
		public virtual string Coursemeta 
		{ 
		    get
		    {
		        return this.coursemeta;
		    }
		    set
		    {
		        this.coursemeta = value;
		    }
		}
		
		private string sourcemeta;
		public virtual string Sourcemeta 
		{ 
		    get
		    {
		        return this.sourcemeta;
		    }
		    set
		    {
		        this.sourcemeta = value;
		    }
		}
		
		private short? isCritical;
		public virtual short? IsCritical 
		{ 
		    get
		    {
		        return this.isCritical;
		    }
		    set
		    {
		        this.isCritical = value;
		    }
		}
		
		private IList<LessonExpectation> lessonExpectations = new List<LessonExpectation>();
		public virtual IList<LessonExpectation> LessonExpectations 
		{ 
		    get
		    {
		        return this.lessonExpectations;
		    }
		}
		
	}
}

namespace lbcLibrary	
{
	public partial class KnowledgeStandard
	{
		private int iD;
		public virtual int ID 
		{ 
		    get
		    {
		        return this.iD;
		    }
		    set
		    {
		        this.iD = value;
		    }
		}
		
		private string kSID;
		public virtual string KSID 
		{ 
		    get
		    {
		        return this.kSID;
		    }
		    set
		    {
		        this.kSID = value;
		    }
		}
		
		private string description;
		public virtual string Description 
		{ 
		    get
		    {
		        return this.description;
		    }
		    set
		    {
		        this.description = value;
		    }
		}
		
		private IList<Lesson> lessons = new List<Lesson>();
		public virtual IList<Lesson> Lessons 
		{ 
		    get
		    {
		        return this.lessons;
		    }
		}
		
	}
}

namespace lbcLibrary	
{
	public partial class LbcUser
	{
		private Guid iD;
		public virtual Guid ID 
		{ 
		    get
		    {
		        return this.iD;
		    }
		    set
		    {
		        this.iD = value;
		    }
		}
		
		private string userName;
		public virtual string UserName 
		{ 
		    get
		    {
		        return this.userName;
		    }
		    set
		    {
		        this.userName = value;
		    }
		}
		
		private string userPassword;
		public virtual string UserPassword 
		{ 
		    get
		    {
		        return this.userPassword;
		    }
		    set
		    {
		        this.userPassword = value;
		    }
		}
		
		private string firstName;
		public virtual string FirstName 
		{ 
		    get
		    {
		        return this.firstName;
		    }
		    set
		    {
		        this.firstName = value;
		    }
		}
		
		private string lastName;
		public virtual string LastName 
		{ 
		    get
		    {
		        return this.lastName;
		    }
		    set
		    {
		        this.lastName = value;
		    }
		}

        public virtual string FullName
        {
            get
            {
                return this.firstName + " " + this.lastName;
            }
        }
		
		private string gender;
		public virtual string Gender 
		{ 
		    get
		    {
		        return this.gender;
		    }
		    set
		    {
		        this.gender = value;
		    }
		}
		
		private string email;
		public virtual string Email 
		{ 
		    get
		    {
		        return this.email;
		    }
		    set
		    {
		        this.email = value;
		    }
		}
		
		private string fTPPath;
		public virtual string FTPPath 
		{ 
		    get
		    {
		        return this.fTPPath;
		    }
		    set
		    {
		        this.fTPPath = value;
		    }
		}
		
		private string accountType;
		public virtual string AccountType 
		{ 
		    get
		    {
		        return this.accountType;
		    }
		    set
		    {
		        this.accountType = value;
		    }
		}
		
		private short? active;
		public virtual short? Active 
		{ 
		    get
		    {
		        return this.active;
		    }
		    set
		    {
		        this.active = value;
		    }
		}
		
		private DateTime? createdOn;
		public virtual DateTime? CreatedOn 
		{ 
		    get
		    {
		        return this.createdOn;
		    }
		    set
		    {
		        this.createdOn = value;
		    }
		}
		
		private DateTime? lastLogin;
		public virtual DateTime? LastLogin 
		{ 
		    get
		    {
		        return this.lastLogin;
		    }
		    set
		    {
		        this.lastLogin = value;
		    }
		}
		
		private IList<CoursePermission> coursePermissions = new List<CoursePermission>();
		public virtual IList<CoursePermission> CoursePermissions 
		{ 
		    get
		    {
		        return this.coursePermissions;
		    }
		}
		
		private IList<LessonMyDescription> lessonMyDescriptions = new List<LessonMyDescription>();
		public virtual IList<LessonMyDescription> LessonMyDescriptions 
		{ 
		    get
		    {
		        return this.lessonMyDescriptions;
		    }
		}
		
		private IList<LessonMyDocument> lessonMyDocuments = new List<LessonMyDocument>();
		public virtual IList<LessonMyDocument> LessonMyDocuments 
		{ 
		    get
		    {
		        return this.lessonMyDocuments;
		    }
		}
		
		private IList<LessonMyMaterial> lessonMyMaterials = new List<LessonMyMaterial>();
		public virtual IList<LessonMyMaterial> LessonMyMaterials 
		{ 
		    get
		    {
		        return this.lessonMyMaterials;
		    }
		}
		
		private IList<LessonMyMHLE> lessonMyMHLEs = new List<LessonMyMHLE>();
		public virtual IList<LessonMyMHLE> LessonMyMHLEs 
		{ 
		    get
		    {
		        return this.lessonMyMHLEs;
		    }
		}
		
		private IList<LessonMyModification> lessonMyModifications = new List<LessonMyModification>();
		public virtual IList<LessonMyModification> LessonMyModifications 
		{ 
		    get
		    {
		        return this.lessonMyModifications;
		    }
		}
		
	}
}

namespace lbcLibrary	
{
	public partial class Lesson
	{
		private Guid iD;
		public virtual Guid ID 
		{ 
		    get
		    {
		        return this.iD;
		    }
		    set
		    {
		        this.iD = value;
		    }
		}
		
		private Guid unitID;
		public virtual Guid UnitID 
		{ 
		    get
		    {
		        return this.unitID;
		    }
		    set
		    {
		        this.unitID = value;
		    }
		}
		
		private string lessonName;
		public virtual string LessonName 
		{ 
		    get
		    {
		        return this.lessonName;
		    }
		    set
		    {
		        this.lessonName = value;
		    }
		}
		
		private int lessonNum;
		public virtual int LessonNum 
		{ 
		    get
		    {
		        return this.lessonNum;
		    }
		    set
		    {
		        this.lessonNum = value;
		    }
		}
		
		private bool? isComplete;
		public virtual bool? IsComplete 
		{ 
		    get
		    {
		        return this.isComplete;
		    }
		    set
		    {
		        this.isComplete = value;
		    }
		}
		
		private string description;
		public virtual string Description 
		{ 
		    get
		    {
		        return this.description;
		    }
		    set
		    {
		        this.description = value;
		    }
		}
		
		private string modifications;
		public virtual string Modifications 
		{ 
		    get
		    {
		        return this.modifications;
		    }
		    set
		    {
		        this.modifications = value;
		    }
		}
		
		private string materials;
		public virtual string Materials 
		{ 
		    get
		    {
		        return this.materials;
		    }
		    set
		    {
		        this.materials = value;
		    }
		}
		
		private string reflection;
		public virtual string Reflection 
		{ 
		    get
		    {
		        return this.reflection;
		    }
		    set
		    {
		        this.reflection = value;
		    }
		}
		
		private string mHLEAS;
		public virtual string MHLEAS 
		{ 
		    get
		    {
		        return this.mHLEAS;
		    }
		    set
		    {
		        this.mHLEAS = value;
		    }
		}
		
		private string mHLEPurpose;
		public virtual string MHLEPurpose 
		{ 
		    get
		    {
		        return this.mHLEPurpose;
		    }
		    set
		    {
		        this.mHLEPurpose = value;
		    }
		}
		
		private string mHLEInput;
		public virtual string MHLEInput 
		{ 
		    get
		    {
		        return this.mHLEInput;
		    }
		    set
		    {
		        this.mHLEInput = value;
		    }
		}
		
		private string mHLEModel;
		public virtual string MHLEModel 
		{ 
		    get
		    {
		        return this.mHLEModel;
		    }
		    set
		    {
		        this.mHLEModel = value;
		    }
		}
		
		private string mHLECFU;
		public virtual string MHLECFU 
		{ 
		    get
		    {
		        return this.mHLECFU;
		    }
		    set
		    {
		        this.mHLECFU = value;
		    }
		}
		
		private string mHLEGP;
		public virtual string MHLEGP 
		{ 
		    get
		    {
		        return this.mHLEGP;
		    }
		    set
		    {
		        this.mHLEGP = value;
		    }
		}
		
		private string mHLEClosure;
		public virtual string MHLEClosure 
		{ 
		    get
		    {
		        return this.mHLEClosure;
		    }
		    set
		    {
		        this.mHLEClosure = value;
		    }
		}
		
		private string mHLEIP;
		public virtual string MHLEIP 
		{ 
		    get
		    {
		        return this.mHLEIP;
		    }
		    set
		    {
		        this.mHLEIP = value;
		    }
		}
		
		private bool? eTRWGender;
		public virtual bool? ETRWGender 
		{ 
		    get
		    {
		        return this.eTRWGender;
		    }
		    set
		    {
		        this.eTRWGender = value;
		    }
		}
		
		private bool? eTRWRacial;
		public virtual bool? ETRWRacial 
		{ 
		    get
		    {
		        return this.eTRWRacial;
		    }
		    set
		    {
		        this.eTRWRacial = value;
		    }
		}
		
		private bool? eTRWDisability;
		public virtual bool? ETRWDisability 
		{ 
		    get
		    {
		        return this.eTRWDisability;
		    }
		    set
		    {
		        this.eTRWDisability = value;
		    }
		}
		
		private bool? eTRWTechnology;
		public virtual bool? ETRWTechnology 
		{ 
		    get
		    {
		        return this.eTRWTechnology;
		    }
		    set
		    {
		        this.eTRWTechnology = value;
		    }
		}
		
		private bool? eTRWResearch;
		public virtual bool? ETRWResearch 
		{ 
		    get
		    {
		        return this.eTRWResearch;
		    }
		    set
		    {
		        this.eTRWResearch = value;
		    }
		}
		
		private bool? eTRWWorkplace;
		public virtual bool? ETRWWorkplace 
		{ 
		    get
		    {
		        return this.eTRWWorkplace;
		    }
		    set
		    {
		        this.eTRWWorkplace = value;
		    }
		}
		
		private int? lessonLink;
		public virtual int? LessonLink 
		{ 
		    get
		    {
		        return this.lessonLink;
		    }
		    set
		    {
		        this.lessonLink = value;
		    }
		}
		
		private bool? isLearningEvent;
		public virtual bool? IsLearningEvent 
		{ 
		    get
		    {
		        return this.isLearningEvent;
		    }
		    set
		    {
		        this.isLearningEvent = value;
		    }
		}
		
		private string dailyObjectives;
		public virtual string DailyObjectives 
		{ 
		    get
		    {
		        return this.dailyObjectives;
		    }
		    set
		    {
		        this.dailyObjectives = value;
		    }
		}
		
		private Unit unit;
		public virtual Unit Unit 
		{ 
		    get
		    {
		        return this.unit;
		    }
		    set
		    {
		        this.unit = value;
		    }
		}
		
		private IList<EssentialSkill> essentialSkills = new List<EssentialSkill>();
		public virtual IList<EssentialSkill> EssentialSkills 
		{ 
		    get
		    {
		        return this.essentialSkills;
		    }
		}
		
		private IList<LessonObjective> lessonObjectives = new List<LessonObjective>();
		public virtual IList<LessonObjective> LessonObjectives 
		{ 
		    get
		    {
		        return this.lessonObjectives;
		    }
		}
		
		private IList<ProcessStandard> processStandards = new List<ProcessStandard>();
		public virtual IList<ProcessStandard> ProcessStandards 
		{ 
		    get
		    {
		        return this.processStandards;
		    }
		}
		
		private IList<LessonExpectation> lessonExpectations = new List<LessonExpectation>();
		public virtual IList<LessonExpectation> LessonExpectations 
		{ 
		    get
		    {
		        return this.lessonExpectations;
		    }
		}
		
		private IList<Document> documents = new List<Document>();
		public virtual IList<Document> Documents 
		{ 
		    get
		    {
		        return this.documents;
		    }
		}
		
		private IList<KnowledgeStandard> knowledgeStandards = new List<KnowledgeStandard>();
		public virtual IList<KnowledgeStandard> KnowledgeStandards 
		{ 
		    get
		    {
		        return this.knowledgeStandards;
		    }
		}
		
		private IList<LessonMyDescription> lessonMyDescriptions = new List<LessonMyDescription>();
		public virtual IList<LessonMyDescription> LessonMyDescriptions 
		{ 
		    get
		    {
		        return this.lessonMyDescriptions;
		    }
		}
		
		private IList<LessonMyDocument> lessonMyDocuments = new List<LessonMyDocument>();
		public virtual IList<LessonMyDocument> LessonMyDocuments 
		{ 
		    get
		    {
		        return this.lessonMyDocuments;
		    }
		}
		
		private IList<LessonMyMaterial> lessonMyMaterials = new List<LessonMyMaterial>();
		public virtual IList<LessonMyMaterial> LessonMyMaterials 
		{ 
		    get
		    {
		        return this.lessonMyMaterials;
		    }
		}
		
		private IList<LessonMyMHLE> lessonMyMHLEs = new List<LessonMyMHLE>();
		public virtual IList<LessonMyMHLE> LessonMyMHLEs 
		{ 
		    get
		    {
		        return this.lessonMyMHLEs;
		    }
		}
		
		private IList<LessonMyModification> lessonMyModifications = new List<LessonMyModification>();
		public virtual IList<LessonMyModification> LessonMyModifications 
		{ 
		    get
		    {
		        return this.lessonMyModifications;
		    }
		}
		
	}
}

namespace lbcLibrary	
{
	public partial class LessonExpectation
	{
		private Guid lessonID;
		public virtual Guid LessonID 
		{ 
		    get
		    {
		        return this.lessonID;
		    }
		    set
		    {
		        this.lessonID = value;
		    }
		}
		
		private long sENumber;
		public virtual long SENumber 
		{ 
		    get
		    {
		        return this.sENumber;
		    }
		    set
		    {
		        this.sENumber = value;
		    }
		}
		
		private short? lessonDOK;
		public virtual short? LessonDOK 
		{ 
		    get
		    {
		        return this.lessonDOK;
		    }
		    set
		    {
		        this.lessonDOK = value;
		    }
		}
		
		private short? unitDOK;
		public virtual short? UnitDOK 
		{ 
		    get
		    {
		        return this.unitDOK;
		    }
		    set
		    {
		        this.unitDOK = value;
		    }
		}
		
		private Expectation expectation;
		public virtual Expectation Expectation 
		{ 
		    get
		    {
		        return this.expectation;
		    }
		    set
		    {
		        this.expectation = value;
		    }
		}
		
		private Lesson lesson;
		public virtual Lesson Lesson 
		{ 
		    get
		    {
		        return this.lesson;
		    }
		    set
		    {
		        this.lesson = value;
		    }
		}
		
	}
}

namespace lbcLibrary	
{
	public partial class LessonObjective
	{
		private Guid iD;
		public virtual Guid ID 
		{ 
		    get
		    {
		        return this.iD;
		    }
		    set
		    {
		        this.iD = value;
		    }
		}
		
		private string number;
		public virtual string Number 
		{ 
		    get
		    {
		        return this.number;
		    }
		    set
		    {
		        this.number = value;
		    }
		}
		
		private string description;
		public virtual string Description 
		{ 
		    get
		    {
		        return this.description;
		    }
		    set
		    {
		        this.description = value;
		    }
		}
		
		private IList<Lesson> lessons = new List<Lesson>();
		public virtual IList<Lesson> Lessons 
		{ 
		    get
		    {
		        return this.lessons;
		    }
		}
		
	}
}

namespace lbcLibrary	
{
	public partial class MyDescription
	{
		private Guid iD;
		public virtual Guid ID 
		{ 
		    get
		    {
		        return this.iD;
		    }
		    set
		    {
		        this.iD = value;
		    }
		}
		
		private string description;
		public virtual string Description 
		{ 
		    get
		    {
		        return this.description;
		    }
		    set
		    {
		        this.description = value;
		    }
		}
		
		private IList<LessonMyDescription> lessonMyDescriptions = new List<LessonMyDescription>();
		public virtual IList<LessonMyDescription> LessonMyDescriptions 
		{ 
		    get
		    {
		        return this.lessonMyDescriptions;
		    }
		}
		
	}
}

namespace lbcLibrary	
{
	public partial class MyMaterial
	{
		private Guid iD;
		public virtual Guid ID 
		{ 
		    get
		    {
		        return this.iD;
		    }
		    set
		    {
		        this.iD = value;
		    }
		}
		
		private string description;
		public virtual string Description 
		{ 
		    get
		    {
		        return this.description;
		    }
		    set
		    {
		        this.description = value;
		    }
		}
		
		private IList<LessonMyMaterial> lessonMyMaterials = new List<LessonMyMaterial>();
		public virtual IList<LessonMyMaterial> LessonMyMaterials 
		{ 
		    get
		    {
		        return this.lessonMyMaterials;
		    }
		}
		
	}
}

namespace lbcLibrary	
{
	public partial class MyMHLE
	{
		private Guid iD;
		public virtual Guid ID 
		{ 
		    get
		    {
		        return this.iD;
		    }
		    set
		    {
		        this.iD = value;
		    }
		}
		
		private string area;
		public virtual string Area 
		{ 
		    get
		    {
		        return this.area;
		    }
		    set
		    {
		        this.area = value;
		    }
		}
		
		private string description;
		public virtual string Description 
		{ 
		    get
		    {
		        return this.description;
		    }
		    set
		    {
		        this.description = value;
		    }
		}
		
		private IList<LessonMyMHLE> lessonMyMHLEs = new List<LessonMyMHLE>();
		public virtual IList<LessonMyMHLE> LessonMyMHLEs 
		{ 
		    get
		    {
		        return this.lessonMyMHLEs;
		    }
		}
		
	}
}

namespace lbcLibrary	
{
	public partial class MyModification
	{
		private Guid iD;
		public virtual Guid ID 
		{ 
		    get
		    {
		        return this.iD;
		    }
		    set
		    {
		        this.iD = value;
		    }
		}
		
		private string description;
		public virtual string Description 
		{ 
		    get
		    {
		        return this.description;
		    }
		    set
		    {
		        this.description = value;
		    }
		}
		
		private IList<LessonMyModification> lessonMyModifications = new List<LessonMyModification>();
		public virtual IList<LessonMyModification> LessonMyModifications 
		{ 
		    get
		    {
		        return this.lessonMyModifications;
		    }
		}
		
	}
}

namespace lbcLibrary	
{
	public partial class ProcessStandard
	{
		private short iD;
		public virtual short ID 
		{ 
		    get
		    {
		        return this.iD;
		    }
		    set
		    {
		        this.iD = value;
		    }
		}
		
		private string pSID;
		public virtual string PSID 
		{ 
		    get
		    {
		        return this.pSID;
		    }
		    set
		    {
		        this.pSID = value;
		    }
		}
		
		private string description;
		public virtual string Description 
		{ 
		    get
		    {
		        return this.description;
		    }
		    set
		    {
		        this.description = value;
		    }
		}
		
		private IList<Lesson> lessons = new List<Lesson>();
		public virtual IList<Lesson> Lessons 
		{ 
		    get
		    {
		        return this.lessons;
		    }
		}
		
	}
}

namespace lbcLibrary	
{
	public partial class Unit
	{
		private Guid iD;
		public virtual Guid ID 
		{ 
		    get
		    {
		        return this.iD;
		    }
		    set
		    {
		        this.iD = value;
		    }
		}
		
		private Guid courseID;
		public virtual Guid CourseID 
		{ 
		    get
		    {
		        return this.courseID;
		    }
		    set
		    {
		        this.courseID = value;
		    }
		}
		
		private string unitName;
		public virtual string UnitName 
		{ 
		    get
		    {
		        return this.unitName;
		    }
		    set
		    {
		        this.unitName = value;
		    }
		}
		
		private int unitNumber;
		public virtual int UnitNumber 
		{ 
		    get
		    {
		        return this.unitNumber;
		    }
		    set
		    {
		        this.unitNumber = value;
		    }
		}
		
		private int? lessonTarget;
		public virtual int? LessonTarget 
		{ 
		    get
		    {
		        return this.lessonTarget;
		    }
		    set
		    {
		        this.lessonTarget = value;
		    }
		}
		
		private int? targetDays;
		public virtual int? TargetDays 
		{ 
		    get
		    {
		        return this.targetDays;
		    }
		    set
		    {
		        this.targetDays = value;
		    }
		}
		
		private string unitGoals;
		public virtual string UnitGoals 
		{ 
		    get
		    {
		        return this.unitGoals;
		    }
		    set
		    {
		        this.unitGoals = value;
		    }
		}
		
		private Course course;
		public virtual Course Course 
		{ 
		    get
		    {
		        return this.course;
		    }
		    set
		    {
		        this.course = value;
		    }
		}
		
		private IList<DistrictObjective> districtObjectives = new List<DistrictObjective>();
		public virtual IList<DistrictObjective> DistrictObjectives 
		{ 
		    get
		    {
		        return this.districtObjectives;
		    }
		}
		
		private IList<Lesson> lessons = new List<Lesson>();
		public virtual IList<Lesson> Lessons 
		{ 
		    get
		    {
		        return this.lessons;
		    }
		}
		
	}
}

namespace lbcLibrary	
{
	public partial class LessonMyDescription
	{
		private Guid lessonID;
		public virtual Guid LessonID 
		{ 
		    get
		    {
		        return this.lessonID;
		    }
		    set
		    {
		        this.lessonID = value;
		    }
		}
		
		private Guid userID;
		public virtual Guid UserID 
		{ 
		    get
		    {
		        return this.userID;
		    }
		    set
		    {
		        this.userID = value;
		    }
		}
		
		private Guid descriptionID;
		public virtual Guid DescriptionID 
		{ 
		    get
		    {
		        return this.descriptionID;
		    }
		    set
		    {
		        this.descriptionID = value;
		    }
		}
		
		private MyDescription myDescription;
		public virtual MyDescription MyDescription 
		{ 
		    get
		    {
		        return this.myDescription;
		    }
		    set
		    {
		        this.myDescription = value;
		    }
		}
		
		private Lesson lesson;
		public virtual Lesson Lesson 
		{ 
		    get
		    {
		        return this.lesson;
		    }
		    set
		    {
		        this.lesson = value;
		    }
		}
		
		private LbcUser lbcUser;
		public virtual LbcUser LbcUser 
		{ 
		    get
		    {
		        return this.lbcUser;
		    }
		    set
		    {
		        this.lbcUser = value;
		    }
		}
		
	}
}

namespace lbcLibrary	
{
	public partial class LessonMyDocument
	{
		private Guid lessonID;
		public virtual Guid LessonID 
		{ 
		    get
		    {
		        return this.lessonID;
		    }
		    set
		    {
		        this.lessonID = value;
		    }
		}
		
		private Guid userID;
		public virtual Guid UserID 
		{ 
		    get
		    {
		        return this.userID;
		    }
		    set
		    {
		        this.userID = value;
		    }
		}
		
		private Guid docID;
		public virtual Guid DocID 
		{ 
		    get
		    {
		        return this.docID;
		    }
		    set
		    {
		        this.docID = value;
		    }
		}
		
		private Document document;
		public virtual Document Document 
		{ 
		    get
		    {
		        return this.document;
		    }
		    set
		    {
		        this.document = value;
		    }
		}
		
		private Lesson lesson;
		public virtual Lesson Lesson 
		{ 
		    get
		    {
		        return this.lesson;
		    }
		    set
		    {
		        this.lesson = value;
		    }
		}
		
		private LbcUser lbcUser;
		public virtual LbcUser LbcUser 
		{ 
		    get
		    {
		        return this.lbcUser;
		    }
		    set
		    {
		        this.lbcUser = value;
		    }
		}
		
	}
}

namespace lbcLibrary	
{
	public partial class LessonMyMaterial
	{
		private Guid lessonID;
		public virtual Guid LessonID 
		{ 
		    get
		    {
		        return this.lessonID;
		    }
		    set
		    {
		        this.lessonID = value;
		    }
		}
		
		private Guid userID;
		public virtual Guid UserID 
		{ 
		    get
		    {
		        return this.userID;
		    }
		    set
		    {
		        this.userID = value;
		    }
		}
		
		private Guid materialID;
		public virtual Guid MaterialID 
		{ 
		    get
		    {
		        return this.materialID;
		    }
		    set
		    {
		        this.materialID = value;
		    }
		}
		
		private MyMaterial myMaterial;
		public virtual MyMaterial MyMaterial 
		{ 
		    get
		    {
		        return this.myMaterial;
		    }
		    set
		    {
		        this.myMaterial = value;
		    }
		}
		
		private Lesson lesson;
		public virtual Lesson Lesson 
		{ 
		    get
		    {
		        return this.lesson;
		    }
		    set
		    {
		        this.lesson = value;
		    }
		}
		
		private LbcUser lbcUser;
		public virtual LbcUser LbcUser 
		{ 
		    get
		    {
		        return this.lbcUser;
		    }
		    set
		    {
		        this.lbcUser = value;
		    }
		}
		
	}
}

namespace lbcLibrary	
{
	public partial class LessonMyMHLE
	{
		private Guid lessonID;
		public virtual Guid LessonID 
		{ 
		    get
		    {
		        return this.lessonID;
		    }
		    set
		    {
		        this.lessonID = value;
		    }
		}
		
		private Guid userID;
		public virtual Guid UserID 
		{ 
		    get
		    {
		        return this.userID;
		    }
		    set
		    {
		        this.userID = value;
		    }
		}
		
		private Guid mHLEID;
		public virtual Guid MHLEID 
		{ 
		    get
		    {
		        return this.mHLEID;
		    }
		    set
		    {
		        this.mHLEID = value;
		    }
		}
		
		private MyMHLE myMHLE;
		public virtual MyMHLE MyMHLE 
		{ 
		    get
		    {
		        return this.myMHLE;
		    }
		    set
		    {
		        this.myMHLE = value;
		    }
		}
		
		private Lesson lesson;
		public virtual Lesson Lesson 
		{ 
		    get
		    {
		        return this.lesson;
		    }
		    set
		    {
		        this.lesson = value;
		    }
		}
		
		private LbcUser lbcUser;
		public virtual LbcUser LbcUser 
		{ 
		    get
		    {
		        return this.lbcUser;
		    }
		    set
		    {
		        this.lbcUser = value;
		    }
		}
		
	}
}

namespace lbcLibrary	
{
	public partial class LessonMyModification
	{
		private Guid lessonID;
		public virtual Guid LessonID 
		{ 
		    get
		    {
		        return this.lessonID;
		    }
		    set
		    {
		        this.lessonID = value;
		    }
		}
		
		private Guid userID;
		public virtual Guid UserID 
		{ 
		    get
		    {
		        return this.userID;
		    }
		    set
		    {
		        this.userID = value;
		    }
		}
		
		private Guid modificationID;
		public virtual Guid ModificationID 
		{ 
		    get
		    {
		        return this.modificationID;
		    }
		    set
		    {
		        this.modificationID = value;
		    }
		}
		
		private MyModification myModification;
		public virtual MyModification MyModification 
		{ 
		    get
		    {
		        return this.myModification;
		    }
		    set
		    {
		        this.myModification = value;
		    }
		}
		
		private Lesson lesson;
		public virtual Lesson Lesson 
		{ 
		    get
		    {
		        return this.lesson;
		    }
		    set
		    {
		        this.lesson = value;
		    }
		}
		
		private LbcUser lbcUser;
		public virtual LbcUser LbcUser 
		{ 
		    get
		    {
		        return this.lbcUser;
		    }
		    set
		    {
		        this.lbcUser = value;
		    }
		}
		
	}
}
#pragma warning restore 1591

