#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;


namespace acManagement	
{
	public partial class LbcDistrict
	{
		private string _districtCode;
		public virtual string DistrictCode 
		{ 
		    get
		    {
		        return this._districtCode;
		    }
		    set
		    {
		        this._districtCode = value;
		    }
		}
		
		private string _districtName;
		public virtual string DistrictName 
		{ 
		    get
		    {
		        return this._districtName;
		    }
		    set
		    {
		        this._districtName = value;
		    }
		}
		
		private string _connectionString;
		public virtual string ConnectionString 
		{ 
		    get
		    {
		        return this._connectionString;
		    }
		    set
		    {
		        this._connectionString = value;
		    }
		}
		
		private bool? _isActive;
		public virtual bool? IsActive 
		{ 
		    get
		    {
		        return this._isActive;
		    }
		    set
		    {
		        this._isActive = value;
		    }
		}
		
		private string _ftpServer;
		public virtual string FtpServer 
		{ 
		    get
		    {
		        return this._ftpServer;
		    }
		    set
		    {
		        this._ftpServer = value;
		    }
		}
		
		private string _ftpUser;
		public virtual string FtpUser 
		{ 
		    get
		    {
		        return this._ftpUser;
		    }
		    set
		    {
		        this._ftpUser = value;
		    }
		}
		
		private string _ftpPass;
		public virtual string FtpPass 
		{ 
		    get
		    {
		        return this._ftpPass;
		    }
		    set
		    {
		        this._ftpPass = value;
		    }
		}
		
	}
}
