#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;


namespace acManagement	
{
	public partial class LbcExpectation
	{
		private short? _source;
		public virtual short? Source 
		{ 
		    get
		    {
		        return this._source;
		    }
		    set
		    {
		        this._source = value;
		    }
		}
		
		private short? _gradeCode;
		public virtual short? Grade_code 
		{ 
		    get
		    {
		        return this._gradeCode;
		    }
		    set
		    {
		        this._gradeCode = value;
		    }
		}
		
		private short? _area;
		public virtual short? Area 
		{ 
		    get
		    {
		        return this._area;
		    }
		    set
		    {
		        this._area = value;
		    }
		}
		
		private short? _course;
		public virtual short? Course 
		{ 
		    get
		    {
		        return this._course;
		    }
		    set
		    {
		        this._course = value;
		    }
		}
		
		private short? _version;
		public virtual short? Version 
		{ 
		    get
		    {
		        return this._version;
		    }
		    set
		    {
		        this._version = value;
		    }
		}
		
		private short? _reference;
		public virtual short? Reference 
		{ 
		    get
		    {
		        return this._reference;
		    }
		    set
		    {
		        this._reference = value;
		    }
		}
		
		private string _seNumber;
		public virtual string Se_number 
		{ 
		    get
		    {
		        return this._seNumber;
		    }
		    set
		    {
		        this._seNumber = value;
		    }
		}
		
		private string _contentArea;
		public virtual string Content_area 
		{ 
		    get
		    {
		        return this._contentArea;
		    }
		    set
		    {
		        this._contentArea = value;
		    }
		}
		
		private string _grade;
		public virtual string Grade 
		{ 
		    get
		    {
		        return this._grade;
		    }
		    set
		    {
		        this._grade = value;
		    }
		}
		
		private string _code;
		public virtual string Code 
		{ 
		    get
		    {
		        return this._code;
		    }
		    set
		    {
		        this._code = value;
		    }
		}
		
		private string _contentStandard;
		public virtual string Content_standard 
		{ 
		    get
		    {
		        return this._contentStandard;
		    }
		    set
		    {
		        this._contentStandard = value;
		    }
		}
		
		private string _goals;
		public virtual string Goals 
		{ 
		    get
		    {
		        return this._goals;
		    }
		    set
		    {
		        this._goals = value;
		    }
		}
		
		private string _dok;
		public virtual string Dok 
		{ 
		    get
		    {
		        return this._dok;
		    }
		    set
		    {
		        this._dok = value;
		    }
		}
		
		private string _seDescription;
		public virtual string Se_description 
		{ 
		    get
		    {
		        return this._seDescription;
		    }
		    set
		    {
		        this._seDescription = value;
		    }
		}
		
		private string _dateModified;
		public virtual string Date_modified 
		{ 
		    get
		    {
		        return this._dateModified;
		    }
		    set
		    {
		        this._dateModified = value;
		    }
		}
		
		private string _dateAdded;
		public virtual string Date_added 
		{ 
		    get
		    {
		        return this._dateAdded;
		    }
		    set
		    {
		        this._dateAdded = value;
		    }
		}
		
		private string _concept;
		public virtual string Concept 
		{ 
		    get
		    {
		        return this._concept;
		    }
		    set
		    {
		        this._concept = value;
		    }
		}
		
		private string _bigIdea;
		public virtual string Big_idea 
		{ 
		    get
		    {
		        return this._bigIdea;
		    }
		    set
		    {
		        this._bigIdea = value;
		    }
		}
		
		private string _courseMeta;
		public virtual string Course_meta 
		{ 
		    get
		    {
		        return this._courseMeta;
		    }
		    set
		    {
		        this._courseMeta = value;
		    }
		}
		
		private string _sourceMeta;
		public virtual string Source_meta 
		{ 
		    get
		    {
		        return this._sourceMeta;
		    }
		    set
		    {
		        this._sourceMeta = value;
		    }
		}
		
		private short? _isCritical;
		public virtual short? IsCritical 
		{ 
		    get
		    {
		        return this._isCritical;
		    }
		    set
		    {
		        this._isCritical = value;
		    }
		}
		
	}
}
