#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;


namespace acManagement	
{
	public partial class LbcExpectationIndex
	{
		private int _source;
		public virtual int Source 
		{ 
		    get
		    {
		        return this._source;
		    }
		    set
		    {
		        this._source = value;
		    }
		}
		
		private int _grade;
		public virtual int Grade 
		{ 
		    get
		    {
		        return this._grade;
		    }
		    set
		    {
		        this._grade = value;
		    }
		}
		
		private int _area;
		public virtual int Area 
		{ 
		    get
		    {
		        return this._area;
		    }
		    set
		    {
		        this._area = value;
		    }
		}
		
		private int _course;
		public virtual int Course 
		{ 
		    get
		    {
		        return this._course;
		    }
		    set
		    {
		        this._course = value;
		    }
		}
		
		private int _version;
		public virtual int Version 
		{ 
		    get
		    {
		        return this._version;
		    }
		    set
		    {
		        this._version = value;
		    }
		}
		
		private string _txtSource;
		public virtual string Txt_source 
		{ 
		    get
		    {
		        return this._txtSource;
		    }
		    set
		    {
		        this._txtSource = value;
		    }
		}
		
		private string _txtGrade;
		public virtual string Txt_grade 
		{ 
		    get
		    {
		        return this._txtGrade;
		    }
		    set
		    {
		        this._txtGrade = value;
		    }
		}
		
		private string _txtArea;
		public virtual string Txt_area 
		{ 
		    get
		    {
		        return this._txtArea;
		    }
		    set
		    {
		        this._txtArea = value;
		    }
		}
		
		private string _txtCourse;
		public virtual string Txt_course 
		{ 
		    get
		    {
		        return this._txtCourse;
		    }
		    set
		    {
		        this._txtCourse = value;
		    }
		}
		
		private int _count;
		public virtual int Count 
		{ 
		    get
		    {
		        return this._count;
		    }
		    set
		    {
		        this._count = value;
		    }
		}
		
		private string _type;
		public virtual string Type 
		{ 
		    get
		    {
		        return this._type;
		    }
		    set
		    {
		        this._type = value;
		    }
		}
		
		private string _revised;
		public virtual string Revised 
		{ 
		    get
		    {
		        return this._revised;
		    }
		    set
		    {
		        this._revised = value;
		    }
		}
		
		private string _codeStart;
		public virtual string CodeStart 
		{ 
		    get
		    {
		        return this._codeStart;
		    }
		    set
		    {
		        this._codeStart = value;
		    }
		}
		
		private string _codeEnd;
		public virtual string CodeEnd 
		{ 
		    get
		    {
		        return this._codeEnd;
		    }
		    set
		    {
		        this._codeEnd = value;
		    }
		}
		
		private string _description;
		public virtual string Description 
		{ 
		    get
		    {
		        return this._description;
		    }
		    set
		    {
		        this._description = value;
		    }
		}
		
		private string _dateAdded;
		public virtual string Date_added 
		{ 
		    get
		    {
		        return this._dateAdded;
		    }
		    set
		    {
		        this._dateAdded = value;
		    }
		}
		
		private string _dateModified;
		public virtual string Date_modified 
		{ 
		    get
		    {
		        return this._dateModified;
		    }
		    set
		    {
		        this._dateModified = value;
		    }
		}
		
	}
}
